export const SEARCH_BOX_COMPONENT_DATA ='SEARCH_BOX_COMPONENT_DATA';
export const SEARCH_BOX_COMPONENT_ID ='SEARCH_BOX_COMPONENT_ID';
export const LOGO_COMPONENT_DATA = 'LOGO_COMPONENT_DATA';
export const HEADERLINK_COMPONENT_DATA ='HEADERLINK_COMPONENT_DATA';
export const MINI_CART_COMPONENT_DATA = 'MINI_CART_COMPONENT_DATA';